name: "Bug Report"
description: "Signaler un bug"
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décrivez le bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Lancer '...'
        2. Observer '...'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: "Python version, OS"
    validations:
      required: false
